version: '3.8'

services:
  nlp-service:
    build: .
    container_name: nodebook-nlp-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
    restart: unless-stopped
    networks:
      - nlp-network

networks:
  nlp-network:
    driver: bridge
