
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app
      - MAIL_USERNAME=postmaster@example.com
      - MAIL_PASSWORD=changeit
      - MAIL_FROM=noreply@mail.example.com
      - MAIL_SERVER=smtp.example.com
      - MAIL_PORT=587
      - MAIL_TLS=true
      - MAIL_SSL=false
      - EMAIL_FEATURES_ENABLED=true
      - PASSWORD_RESET_EXPIRY_HOURS=1
      - MAX_LOGIN_ATTEMPTS=5
      - ACCOUNT_LOCKOUT_MINUTES=30
      - PASSWORD_MIN_LENGTH=8
      - ALLOWED_ORIGINS=https://example.com, https://api.example.com
    volumes:
      - ./graph_data:/app/graph_data
      - ./logs:/app/logs
    restart: unless-stopped
    command: >
      sh -c "python backend/scripts/post_install.py &&
             uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=https://api.nodebook.co.in
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
