version: '3.8'

services:
  nodebook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - nodebook-data:/data
    restart: unless-stopped

volumes:
  nodebook-data:
