version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"      # Changed from 80 to 8080
      - "8443:443"     # Changed from 443 to 8443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --force-renewal --email your-email@example.com --agree-tos --no-eff-email -d your-domain.com

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"    # Changed from 8000 to 8001
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./graph_data:/app/graph_data
      - ./logs:/app/logs
    restart: unless-stopped
    command: ["sh", "-c", "python scripts/post_install.py && uvicorn main:app --host 0.0.0.0 --port 8000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"    # Changed from 3000 to 3001
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8001
    restart: unless-stopped

  # Development version with hot reload
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8002:8000"    # Changed from 8001 to 8002
    volumes:
      - ./backend:/app
      - ./graph_data:/app/graph_data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    command: ["sh", "-c", "python scripts/post_install.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
    profiles:
      - dev

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"    # Changed from 3001 to 3002
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8002
    command: ["npm", "run", "dev"]
    profiles:
      - dev 