

services:
  # Backend service with authentication and data management
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nodebook-backend-dev
    command: sh -c "cd nodebook-base && node server.js"
    working_dir: /app
    volumes:
      - ./nodebook-base:/app/nodebook-base
      - /app/nodebook-base/node_modules
      - nodebook-dev-data:/app/nodebook-base/user_data
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - JWT_SECRET=dev-jwt-secret-change-in-production
      - JWT_EXPIRES_IN=7d
      - SESSION_SECRET=dev-session-secret-change-in-production
      - HYPERSWARM_PORT=49737
    networks:
      - nodebook-dev-net

  # Frontend service with PWA development
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nodebook-frontend-dev
    command: sh -c "cd nodebook-base/frontend && npm run dev -- --host 0.0.0.0 --port 5173"
    working_dir: /app
    volumes:
      - ./nodebook-base:/app/nodebook-base
      - /app/nodebook-base/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_TARGET=http://backend:3000
      - VITE_DEV_MODE=true
    networks:
      - nodebook-dev-net
    depends_on:
      - backend

networks:
  nodebook-dev-net:
    driver: bridge

volumes:
  # Persistent storage for user data
  nodebook-dev-data:
    driver: local