services:
  backend:
    image: node:20
    container_name: nodebook-backend-dev
    command: sh -c "npm install -g node-gyp nodemon && npm install && npm run dev"
    working_dir: /app/nodebook-base
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    networks:
      - nodebook-dev-net

  frontend:
    image: node:20-slim
    container_name: nodebook-frontend-dev
    command: sh -c "npm install && npm run dev -- --host"
    working_dir: /app
    volumes:
      - ./nodebook-base/frontend:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_TARGET=http://backend:3000
    depends_on:
      - backend
    networks:
      - nodebook-dev-net

networks:
  nodebook-dev-net:
    driver: bridge