

services:
  # Backend service with authentication and data management
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nodebook-backend-dev
    command: sh -c "cd nodebook-base && node server.js"
    working_dir: /app
    volumes:
      - ./nodebook-base:/app/nodebook-base
      - /app/nodebook-base/node_modules
      - nodebook-dev-data:/app/nodebook-base/user_data
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - JWT_SECRET=dev-jwt-secret-change-in-production
      - JWT_EXPIRES_IN=7d
      - SESSION_SECRET=dev-session-secret-change-in-production
      - HYPERSWARM_PORT=49737
    networks:
      - nodebook-dev-net

  # Media backend service for file uploads and management
  media-backend:
    build:
      context: ./media-backend
      dockerfile: Dockerfile
    container_name: nodebook-media-backend-dev
    ports:
      - "3001:3001"
    volumes:
      - ./media-backend/media-data:/app/media-data
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATA_PATH=/app/media-data
    networks:
      - nodebook-dev-net
    restart: unless-stopped

  # NLP service for text analysis and graph suggestions
  nlp-service:
    build:
      context: ./nlp-service
      dockerfile: Dockerfile
    container_name: nodebook-nlp-service-dev
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
    networks:
      - nodebook-dev-net
    restart: unless-stopped

  # WordNet service for auto-filling node descriptions
  wordnet-service:
    build:
      context: ./wordnet-service
      dockerfile: Dockerfile
    container_name: nodebook-wordnet-service-dev
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
    networks:
      - nodebook-dev-net
    restart: unless-stopped

  # Frontend service with PWA development
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nodebook-frontend-dev
    command: sh -c "cd nodebook-base/frontend && npm run dev -- --host 0.0.0.0 --port 5173"
    working_dir: /app
    volumes:
      - ./nodebook-base:/app/nodebook-base
      - /app/nodebook-base/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_TARGET=http://backend:3000
      - VITE_MEDIA_BACKEND_URL=http://localhost:3001
      - VITE_NLP_SERVICE_URL=http://localhost:3002
      - VITE_WORDNET_SERVICE_URL=http://localhost:3003
      - VITE_DEV_MODE=true
    networks:
      - nodebook-dev-net
    depends_on:
      - backend
      - media-backend
      - nlp-service
      - wordnet-service

networks:
  nodebook-dev-net:
    driver: bridge

volumes:
  # Persistent storage for user data
  nodebook-dev-data:
    driver: local