version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./graph_data:/app/graph_data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    command: ["sh", "-c", "python scripts/post_install.py && uvicorn main:app --host 0.0.0.0 --port 8000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    restart: unless-stopped

  # Development version with hot reload
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - ./graph_data:/app/graph_data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    command: ["sh", "-c", "python scripts/post_install.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
    profiles:
      - dev

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8001
    command: ["npm", "run", "dev"]
    profiles:
      - dev 