services:
  # Keycloak Authentication Service
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: nodebook-keycloak-p2p-dev
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_DB=dev-file
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=8080
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - nodebook-p2p-net
    restart: unless-stopped
    command: ["start-dev"]

  # P2P NodeBook Backend Service
  nodebook-p2p:
    build:
      context: ./nodebook-base
      dockerfile: Dockerfile.p2p
    container_name: nodebook-p2p-dev
    volumes:
      - ./nodebook-base:/app
      - /app/node_modules
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - P2P_ENABLED=true
      - COLLABORATION_ENABLED=true
      - LOG_LEVEL=info
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=nodebook
      - DATA_PATH=/app/data
      - DISABLE_AUTH=true
    networks:
      - nodebook-p2p-net
    depends_on:
      - keycloak
    restart: unless-stopped

  # P2P Network Monitor Service
  p2p-monitor:
    build:
      context: ./nodebook-base
      dockerfile: Dockerfile.p2p-monitor
    container_name: nodebook-p2p-monitor-dev
    ports:
      - "3004:3003"
    volumes:
      - ./nodebook-base:/app
      - /app/node_modules
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - MONITOR_PORT=3003
      - P2P_NETWORK_ID=nodebook-dev
      - DATA_PATH=/app/data
    networks:
      - nodebook-p2p-net
    depends_on:
      - nodebook-p2p
    restart: unless-stopped

  # Media backend service for file uploads and management
  media-backend:
    build:
      context: ./media-backend
      dockerfile: Dockerfile
    container_name: nodebook-media-backend-p2p-dev
    ports:
      - "3001:3001"
    volumes:
      - ./data/media:/app/media-data
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATA_PATH=/app/media-data
    networks:
      - nodebook-p2p-net
    restart: unless-stopped

  # Y.js Signaling Server for WebRTC Collaboration
  signaling-server:
    build:
      context: ./nodebook-base
      dockerfile: Dockerfile.p2p
    container_name: nodebook-signaling-server-dev
    ports:
      - "4444:4444"
    volumes:
      - ./nodebook-base:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4444
    networks:
      - nodebook-p2p-net
    restart: unless-stopped
    command: ["node", "signaling-server.js"]

  # NLP service for text analysis and graph suggestions
  nlp-service:
    build:
      context: ./nlp-service
      dockerfile: Dockerfile
    container_name: nodebook-nlp-service-p2p-dev
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
    networks:
      - nodebook-p2p-net
    restart: unless-stopped

  # WordNet service for auto-filling node descriptions
  wordnet-service:
    build:
      context: ./wordnet-service
      dockerfile: Dockerfile
    container_name: nodebook-wordnet-service-p2p-dev
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
    networks:
      - nodebook-p2p-net
    restart: unless-stopped

  # Frontend service with PWA development
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nodebook-frontend-p2p-dev
    command: sh -c "cd nodebook-base/frontend && npm run dev -- --host 0.0.0.0 --port 5173"
    working_dir: /app
    volumes:
      - ./nodebook-base:/app/nodebook-base
      - /app/nodebook-base/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_TARGET=http://nodebook-p2p:3000
      - VITE_KEYCLOAK_URL=http://localhost:8080
      - VITE_KEYCLOAK_REALM=nodebook
      - VITE_KEYCLOAK_CLIENT_ID=nodebook-frontend
      - VITE_KEYCLOAK_CLIENT_SECRET=nodebook-frontend-secret
      - VITE_MEDIA_BACKEND_URL=http://localhost:3001
      - VITE_NLP_SERVICE_URL=http://localhost:3002
      - VITE_WORDNET_SERVICE_URL=http://localhost:3003
      - VITE_P2P_ENABLED=true
      - VITE_DEV_MODE=true
    networks:
      - nodebook-p2p-net
    depends_on:
      - nodebook-p2p
      - keycloak
      - media-backend
      - nlp-service
      - wordnet-service
    restart: unless-stopped

networks:
  nodebook-p2p-net:
    driver: bridge

volumes:
  # Keycloak data persistence
  keycloak-data:
    driver: local
