version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"      # Changed from 80 to 8080
      - "8443:443"     # Changed from 443 to 8443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --force-renewal --email nagarjun@livingAcademy.org --agree-tos --no-eff-email -d nodebook.co.in

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8001:8000"    # Changed from 8000 to 8001
    environment:
      - PYTHONPATH=/app
      # Email Configuration
      - MAIL_USERNAME=admin@mg.nodebook.co.in
      - MAIL_PASSWORD=${MAIL_PASSWORD:-your-mailgun-api-key}
      - MAIL_FROM=noreply@mg.nodebook.co.in
      - MAIL_SERVER=smtp.mailgun.org
      - MAIL_PORT=587
      - MAIL_TLS=true
      - MAIL_SSL=false
      - EMAIL_FEATURES_ENABLED=true
      # Security Configuration
      - PASSWORD_RESET_EXPIRY_HOURS=${PASSWORD_RESET_EXPIRY_HOURS:-1}
      - MAX_LOGIN_ATTEMPTS=${MAX_LOGIN_ATTEMPTS:-5}
      - ACCOUNT_LOCKOUT_MINUTES=${ACCOUNT_LOCKOUT_MINUTES:-30}
      - PASSWORD_MIN_LENGTH=${PASSWORD_MIN_LENGTH:-8}
    volumes:
      - ./graph_data:/app/backend/graph_data
      - ./logs:/app/backend/logs
    restart: unless-stopped
    command: ["sh", "-c", "python -m backend.scripts.post_install && uvicorn backend.main:app --host 0.0.0.0 --port 8000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 30s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"    # Changed from 3000 to 3001
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8001
    restart: unless-stopped
