site_name: NodeBook Backend Documentation
site_description: Comprehensive documentation for the NodeBook backend API and implementation
site_author: NodeBook Team
site_url: https://nodebook.github.io/

# Repository
repo_name: gnowgi/nodebook.github.io
repo_url: https://github.com/gnowgi/nodebook.github.io
edit_uri: edit/main/docs/docs/

# Theme
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

# Plugins
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [..]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_signature_annotations: true
            show_bases: true
            heading_level: 2
            members_order: source
            docstring_style: google
  - autorefs

# Navigation
nav:
  - Home: index.md
  - API Reference:
    - Core Modules:
      - Models: api/core/models.md
      - Utils: api/core/utils.md
      - Registry: api/core/registry.md
    - Schema Operations:
      - Schema Operations: api/core/schema_ops.md
      - Schema Utilities: api/core/schema_utils.md
      - Schema Management: api/routes/schema_routes.md
    - Node Operations:
      - Node Utils: api/core/node_utils.md
      - Node Management: api/routes/nodes.md
      - NDF Routes: api/routes/ndf_routes.md
      - Parse Pipeline: api/routes/parse_pipeline.md
    - NBH Operations:
      - Graph Operations: api/routes/graph_ops.md
      - Graph Management: api/routes/graphs.md
      - Graph Routes: api/routes/graph.md
      - Graph Transitions: api/routes/transitions.md
    - System Operations:
      - Atomic Operations: api/core/atomic_ops.md
      - Atomic Routes: api/routes/atomic_routes.md
      - User Management: api/routes/users.md
      - Functions: api/routes/functions.md
      - Preferences: api/routes/preferences.md
      - Logging: api/routes/logging.md
    - Third Party Operations:
      - User Registration/Authentication: api/external/auth.md
      - NLP Support: api/external/nlp.md
      - LLM Endpoints: api/external/llm.md
      - Documentation: api/external/docs.md
      - Cytoscape Integration: api/external/cytoscape.md
      - Database Operations: api/external/database.md
      - File System Operations: api/external/filesystem.md
      - Network Operations: api/external/network.md
  - Development:
    - Installation: development/installation.md

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS and JS
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Copyright
copyright: Copyright &copy; 2025 NodeBook Team
