name: Deploy to nodebook.github.io

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'backend/**', '.github/workflows/deploy-to-pages.yml' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocstrings[python] mkdocs-material

      - name: Install spaCy model
        run: |
          python -m spacy download en_core_web_sm

      - name: Build documentation
        run: |
          cd docs
          mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
          external_repository: nodebook/nodebook.github.io
          publish_branch: main
          force_orphan: true 